"""Clients and user relation one one created

Revision ID: 5faa6fa1df70
Revises: 50f09a124d85
Create Date: 2024-11-29 12:09:08.670294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5faa6fa1df70'
down_revision: Union[str, None] = '50f09a124d85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('client_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
