"""added Clients model

Revision ID: fd8c7fdfaa3d
Revises: e1247c3c195e
Create Date: 2024-11-28 19:22:22.772494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8c7fdfaa3d'
down_revision: Union[str, None] = 'e1247c3c195e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
